server:
  port: 8080


logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-3-38-186-84.ap-northeast-2.compute.amazonaws.com:3306/likelion-db #jdbc:mysql://localhost:3306/likelion-db
    username: root
    password: 12345678

